- hosts: localhost
  become: yes
  connection: local

  tasks:

   - name: set state and environment and AWS_ACCT values
     set_fact: 
         state: "{{ snow_payload['state'] | upper }}"
         env: "{{ snow_payload['environment'] }}"
         aws_acct: "{{ snow_payload['aws_acct'] }}"

   - name: create and launch resource template in awx 
     include_tasks: 
             file: launch_resource_template.yml
